[package]
name = "kero-desktop-pet"
version = "0.1.0"
description = "A tiny Kero desktop pet."
authors = ["Rafael"]
edition = "2021"

[lib]
name = "kero_desktop_pet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
